# -*- coding: utf-8 -*-
"""Maximum_Sum_Sub-sequence.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18mUdsTse8_fcVmAwfcXm6b2ram61PytO
"""

def MaxNonEmpSubSeq(a, n):
    sum = 0
    maxm = max(a)
    if (maxm <= 0):
        return maxm
    for i in range(n):
        if (a[i] > 0):
            sum += a[i]
    return sum
a=[int (x) for x in input ().split()]
N = len(a)
print(MaxNonEmpSubSeq(a, N))